[package]
name = "native_stablecoin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
shared_memory = { path = "../shared_memory", features = ["native-bridge"] }
solana-program = "1.18.26"
bytemuck = { version = "1.18.0", features = ["derive", "min_const_generics"] }
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
pyth-sdk-solana = "0.10.6"
