[features]
seeds = false

[programs.localnet]
anchor_stablecoin = "programs/anchor_stablecoin"
native_stablecoin = "programs/native_stablecoin"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"
