apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orchestrator-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: orchestrator-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /prod/stablecoin/database_url
